name: netflixapp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4 # provider package
  responsive_sizer: ^3.1.1 # responsive sizer package
  google_fonts: ^3.0.1 # google fonts package
  video_player: ^2.4.7 # video player package
  youtube_player_iframe: ^2.2.0 # youtube player package
  # youtube_player_flutter: ^8.1.1 #
  


  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  


flutter:

  
  uses-material-design: true
  assets:
    - assets/comingsoon/
   
    - assets/search/
    - assets/bottomnavigationbar/
    - assets/

